name: 'Log Monitor Test'
description: 'Simple test action for log monitoring'
author: 'Your Name'

inputs:
  runner-id:
    description: 'Unique identifier for this workflow run'
    required: true
    default: ''
  server-url:
    description: 'URL of the log monitoring server'
    required: true
    default: 'http://129.154.46.198:3000'
  github-token:
    description: 'GitHub token for authentication'
    required: true
    default: ''

runs:
  using: 'composite'
  steps:
    - name: Send test log
      shell: bash
      run: |
        # Set default runner-id if not provided
        if [ -z "${{ inputs.runner-id }}" ]; then
          RUNNER_ID="${{ github.run_id }}-${{ github.run_attempt }}"
        else
          RUNNER_ID="${{ inputs.runner-id }}"
        fi
        
        SERVER_URL="${{ inputs.server-url }}"
        TOKEN="${{ inputs.github-token }}"
        
        echo "Testing connection to: $SERVER_URL/$RUNNER_ID"
        
        # Send simple test data
        TEST_DATA='{
          "workflow": "${{ github.workflow }}",
          "job": "${{ github.job }}",
          "repository": "${{ github.repository }}",
          "status": "started",
          "timestamp": "'$(date -u +"%Y-%m-%dT%H:%M:%SZ")'"
        }'
        
        echo "Sending test data: $TEST_DATA"
        
        # Send request
        RESPONSE=$(curl -s -X POST \
          -H "Content-Type: application/json" \
          -H "Authorization: Bearer $TOKEN" \
          -d "$TEST_DATA" \
          "$SERVER_URL/$RUNNER_ID")
        
        echo "Server response: $RESPONSE"
        
        # Also test stream endpoint
        STREAM_RESPONSE=$(curl -s -X POST \
          -H "Content-Type: application/json" \
          -H "Authorization: Bearer $TOKEN" \
          -d '{"message": "Test stream log", "level": "info"}' \
          "$SERVER_URL/$RUNNER_ID/stream")
        
        echo "Stream response: $STREAM_RESPONSE"
