name: 'Workflow Log Monitor'
description: 'Register workflow with log monitoring server'
inputs:
  server-url:
    description: 'URL of the log monitoring server'
    required: true
    default: 'http://129.154.46.198:3000'

runs:
  using: 'composite'
  steps:
    - name: Register workflow with log server
      shell: bash
      run: |
        RUNNER_ID="${{ github.run_id }}-${{ github.run_attempt }}"
        SERVER_URL="${{ inputs.server-url }}"
        
        echo "ðŸš€ Registering workflow with log server..."
        echo "ðŸ“‹ Runner ID: ${RUNNER_ID}"
        echo "ðŸ· Repository: ${{ github.repository }}"
        echo "ðŸ”§ Workflow: ${{ github.workflow }}"
        echo "ðŸ’¼ Job: ${{ github.job }}"
        
        # Send workflow info to server
        RESPONSE=$(curl -s -X POST \
          -H "Content-Type: application/json" \
          -d "{
            \"repository\": \"${{ github.repository }}\",
            \"workflow\": \"${{ github.workflow }}\",
            \"job\": \"${{ github.job }}\",
            \"timestamp\": \"$(date -u +'%Y-%m-%dT%H:%M:%SZ')\"
          }" \
          "${SERVER_URL}/${RUNNER_ID}")
        
        echo "ðŸ“¨ Server response: ${RESPONSE}"
        
        # Export runner ID
        echo "RUNNER_ID=${RUNNER_ID}" >> $GITHUB_ENV
        echo "LOG_SERVER=${SERVER_URL}" >> $GITHUB_ENV
        
        echo ""
        echo "ðŸ“‹ Next steps to fetch logs:"
        echo "1. Wait for workflow to complete"
        echo "2. Check status: curl ${SERVER_URL}/${RUNNER_ID}/status"
        echo "3. Fetch logs manually: curl -X POST ${SERVER_URL}/${RUNNER_ID}/fetch -H 'Content-Type: application/json' -d '{\"token\": \"YOUR_GITHUB_TOKEN\"}'"
